name: Gdformat

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gdformat-check:
    name: 'Gdformat check'
    runs-on: ubuntu-latest
    outputs:
      NEEDS_FORMAT: ${{ steps.check-format.outputs.NEEDS_FORMAT }}
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - id: check-format
      run: |
        gdformat --check $(find ./src/ -name '*.gd' -not -path "./src/addons/*")
        echo "NEEDS_FORMAT=$?" >> "$GITHUB_OUTPUT"
  gdformat-format:
    name: 'Gdformat format'
    runs-on: ubuntu-latest
    needs: gdformat-check
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: Scony/godot-gdscript-toolkit@master
      - env:
          NEEDS_FORMAT: ${{ needs.gdformat-check.outputs.NEEDS_FORMAT }}
        run: |
          if [ "$NEEDS_FORMAT" -eq "1" ]; then
            gdformat $(find ./src/ -name '*.gd' -not -path "./src/addons/*")
          else
            echo "format not needed, code $NEEDS_FORMAT"
          fi
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated formatting"
